# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d9f74ad3c923344e88c535feb8958730d34c956a3442715e0881bcd3c677d61748eb51698816cb7220018f8cf73f4e6831f4e4b763b171c7d2aefe1f64db1f5

test:
  secret_key_base: e2c870b0c2c26f2514c0ca8da8826e643bdba0a476b31004f3dd823e07249cbd3f62dca22b76b05408bbcf97588393ac39c59323f322aeb8aea1aee848d39c7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
